Login UI (ChicoState#3)
ChicoState/StudyGroup pull request #18
Opened 2020-02-23 08:04 UTC by asheelamagwili

Basic login UI implemented in _lib/auth/login.dart_ , followed general styling direction by @bmarden . This file also contains comments of my current test codes for Google Authentication (commented out). Should be able to run it and see the login UI if:

`home: LoginPage(title: 'Login'),`

is uncommented in _main.dart_ and 

`home: HomePage(title: 'Study Buddy App'), // Placeholder title for now`

is commented out.

2020-02-23 08:16 UTC, lrondenet reviewed
Looks Good!

2020-02-23 08:16 UTC, lrondenet approved these changes

2020-02-23 08:24 UTC, e7ite approved these changes
Freakin' awesome job!

2020-02-23 17:51 UTC, bmarden requested changes

2020-02-23 17:51 UTC, bmarden commented on study_group_app/lib/screens/auth/login.dart
> +        padding: EdgeInsets.fromLTRB(20, 300, 20, 40),
I'm getting bottom overflow from this when the keyboard is brought up. Could change it to this to fix that issue and then we can reposition the text boxes later if we want. 
```suggestion
        padding: EdgeInsets.all(20),
```

2020-02-24 20:08 UTC, bmarden approved these changes
Looks good

2020-02-24 20:09 UTC, merged