Added Firebase discussion tab integration
ChicoState/StudyGroup pull request #56
Opened 2020-05-06 12:03 UTC by e7ite

Big thanks to Ben on this one!

2020-05-06 19:36 UTC, lrondenet approved these changes

2020-05-06 20:03 UTC, asheelamagwili approved these changes

2020-05-06 21:07 UTC, bmarden requested changes
I fixed the merge conflicts but it's still failing the linting from TravisCI. Make sure you pull from your branch again, cause I pushed the fixed merge conflicts to your origin, and then just go through and fix the linting errors and re-push. The build will run again and check for linting errors again. Lmk if you need help.

2020-05-07 02:16 UTC, e7ite commented
Fixed the linting errors. All checks seemed to pass finally.

2020-05-07 02:18 UTC, bmarden approved these changes

2020-05-07 02:18 UTC, merged